services:
  db:
    image: postgres:16
    container_name: ums_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ums
      POSTGRES_PASSWORD: ums
      POSTGRES_DB: umsdb
    ports:
      - '5433:5432' # <-- cambias 5432 a 5433 en el host
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: ums_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.test
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8081:80'
    depends_on:
      - db

volumes:
  db_data:
